#' Generate Table of Coefficients
#'
#' This function takes the fits from either the empirical example or sim study and generates the table of coefficients and returns the parameter estimate, standard error, t-value and p-value.
#' @param fit The fit generated by getFits of the illegal immigrant data set.
#' @param weather Whether or not weather was included in the fitting process. Defaults to FALSE.
#' @param sim Is the fit from the simulation study or the empirical example? Defaults to FALSE for empirical example fit.
#' @param xtable Should results be returned in xtable format? Defaults to FALSE.
#' @keywords output
#' @export
#' @examples
#' CoefTable()

CoefTable <- function(fit, weather = FALSE, sim = FALSE, xtable = FALSE) {
    pe <- fit$par                # point estimates
    vc <- solve(fit$hessian)     # var-cov matrix
    se <- sqrt(diag(vc))                 # standard errors
    ll <- -fit$value             # likelihood at maximum
    t.val <- pe/se
    p.val <- 2*pnorm(abs(t.val), lower = FALSE)

    optim.result.table<-round(cbind(pe,se, t.val, p.val),3)
    if (sim == TRUE){
        cov.names <- c("Intercept", "Coef 1", "Coef 2", "Coef 3", "Coef 4")
        } else if (weather == TRUE){
            cov.names <- c("Intercept", "Gender", "Age", "Turkey", "North Africa", "Africa", "Surinam", "East Europe", "Asia", "America", "Amsterdam", "Den Haag", "Rotterdam", "Utrecht", "Weather")
        } else {
            cov.names <- c("Intercept", "Gender", "Age", "Turkey", "North Africa", "Africa", "Surinam", "East Europe", "Asia", "America", "Amsterdam", "Den Haag", "Rotterdam", "Utrecht")
        }

    rownames(optim.result.table)<- cov.names
    if(xtable == TRUE){
        return(xtable(optim.result.table))
    }else{
        return(print(optim.result.table))
    }
}