#' Display the Empirical Output results
#'
#' This function takes the fits generated by the empirical output analysis and displays the results.
#' @param fits Fits from getFits()
#' @keywords output
#' @export
#' @examples
#' DisplayEmpiricalOutput()

DisplayEmpiricalOutput <- function(fits) {
    all.three <- cbind(CoefTable(fits$out.fv, weather = TRUE)[,1:2], CoefTable(fits$out.nv, weather = TRUE)[,1:2], CoefTable(fits$out.pr, weather = TRUE)[,1:2])
    nhats <- NHatTable(fits)


    return(list(all.three, nhats))
}