#' Display the Simulation Study results
#'
#' This function takes the result files generated by the simulation study analysis and displays the results.
#' @param N Total number of simulation iterations.
#' @keywords output, simulation
#' @export
#' @examples
#' DisplaySimOutput()

DisplaySimOutput <- function(N) {
    sim.res.one <- read.table(file = "Results/simulation.1.results.txt")
    sim.res.two <- read.table(file = "Results/simulation.2.results.txt")

    pars.one <- GetSimPars(sim.res.one[1:15], c(-7, -.5, -.25, .25, .5), FALSE)
    pars.two <- GetSimPars(sim.res.two[1:15], c(-7, -.5, -.25, .25, .5), FALSE)

    nhats.one <- GetSimNhats(sim.res.one[16:21], N)
    nhats.two <- GetSimNhats(sim.res.two[16:21], N)

    return(list(pars.one, pars.two, nhats.one, nhats.two))
}