#' Save Simulation Data
#'
#' Takes the data generated by the simulation study and saves it in files.
#' @param data List of all three methods and estimated coefficients followed by nhats.
#' @param sim.name Which method was used (1 or 2)
#' @keywords output, simulation
#' @export
#' @examples
#' SaveData()

SaveData <- function(data, sim.name) {
    par.names <- c("Intercept", "z1", "z2", "z3", "z4")
    cond.names <- c("PE", "IS", "PR")

    par.cols <- paste(rep(cond.names, each = 5), rep(par.names, 3), sep = ".")
    nhat.cols <- paste(rep(cond.names, each = 2), rep(c("nhat", "var"), 3), sep = ".")
    where <- paste0("Results/simulation.", sim.name, ".results.txt")
    write.table(data, where, col.names = c(par.cols, nhat.cols))
}